# Generated by Django 4.1.7 on 2023-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
