# Generated by Django 4.1.7 on 2023-04-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
